DefaultContentLanguage = "en"
baseURL = "https://usrpro.com/"
theme = "dot"
enableGitInfo = true

# customize color
[params]
primaryColor = "#02007e"
secondaryColor = "#f9f9f9"
textColor = "#636363"
textColorDark = "#242738"
whiteColor = "#ffffff"

[Languages]

  # English Language
  [Languages.en]
  languageName = "en"
  weight = 1
  languageCode = "en-us"
  title = "USRPRO - Profesional Mailu contributors"
  dateFormat = "2 January 2006"
  home = "Home"
  logo = "/usr/pro"
  copyright = 'Content on this website is Copyright © Mohlmann Solutions SRL 2019.'
  license = 'Licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License.'

    # navigation
    [Languages.en.menu]

      [[Languages.en.menu.main]]
        weight = 1
        name = "Publications"
        url = "publications"

      [[Languages.en.menu.main]]
        weight = 2
        name = "Projects"
        url = "/projects"
        hasChildren = true

          [[Languages.en.menu.main]]
          parent = "Projects"
          weight = 1
          name = "RESTful API"
          url = "/projects/restful-api"

      [[Languages.en.menu.main]]
        weight = 3
        name = "About"
        url = "/about"
        hasChildren = true

          [[Languages.en.menu.main]]
          parent = "About"
          weight = 1
          name = "Company"
          url = "/about/company"
          
          [[Languages.en.menu.main]]
          parent = "About"
          weight = 2
          name = "Roadmaps"
          url = "/about/projects-roadmap"

          [[Languages.en.menu.main]]
          parent = "About"
          weight = 3
          name = "Copyright info"
          url = "/about/copyright-and-licensing"

      [[Languages.en.menu.main]]
        weight = 4
        name = "Contact"
        url = "/#contact"

    # banner
    [Languages.en.params.banner]
      title = "Profesional Mailu contributors"
      description = "We provide commercial support, improvements and hosting plans"
      image = "images/banner.jpg"

    # Topics
    [Languages.en.params.topics]
      title = "Discover"

    # contact
    [Languages.en.params.contact]
      title = "Got Any Questions?"
      content = "Send us a message and we will get back to you."

    # footer social icon
     [[Languages.en.socialIcon]]
      logo_icon =  "/images/logo_svg.svg"
      linkURL = "https://mohlmann.solutions/"

    [[Languages.en.socialIcon]]
      icon = "ti-facebook"
      linkURL = "https://www.facebook.com/mohlmann.solutions/"

    [[Languages.en.socialIcon]]
      icon = "ti-linkedin"
      linkURL = "https://www.linkedin.com/company/mohlmann-solutions-srl"

    [[Languages.en.socialIcon]]
      icon = "ti-github"
      linkURL = "https://github.com/usrpro"


